### ISSUE TITLE
Incorrect sprite URLs

### ISSUE THREAD

**Issue by ChrisMash** [PokeAPI/api-data#108]
Something's gone wrong lately with the sprite URLs, they're a malformed concatenation of a partial URL followed by the full URL, e.g.:

https://raw.githubusercontent.com/PokeAPI/sprites/master/https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/1.png

Note the https:// in the middle of the URL

Seems like it affects every single sprite URL
See https://github.com/PokeAPI/api-data/blob/master/data/api/v2/pokemon-form/1/index.json as an example

**Comment by Naramsim** [comment]
Hi, yes, currently the HEAD of this repo is broken. I have a patch to merge to fix this problem. 

If you use the API everything is fine. If using this repo, checkout HEAD~1, I guess.

**Comment by Naramsim** [comment]
issue should be closed now
