### ISSUE TITLE
Occasionally a resource list request returns a 400 response

### ISSUE THREAD

**Issue by sargunv** [PokeAPI/api-data#11]
A retry always works.

The error is from this code:

 https://github.com/PokeAPI/api-data/blob/2e21d03fd71f00f091f92671940227013b296277/functions/resource-list.js#L78-L83 

Looks like sometimes the endpoint name isn't being passed to the function. May be another Netlify bug.

**Comment by tdmalone** [comment]
Is this related?
https://pokeapi.netlify.com/api/v2/pokemon/
Doesn't work on a retry, though.

**Comment by sargunv** [comment]
> Is this related?

There was a temporary similar issue caused by the broken builds + name change which caused all resource list requests to fail until a build with the new name succeeded.

Now that we've had a successful build, it's back to the issue in the OP.
