### ISSUE TITLE
 Incorrect text for leftovers in the Spanish version group x-y

### ISSUE THREAD

**Issue by Xing97** [PokeAPI/api-data#227]
https://github.com/PokeAPI/api-data/blob/master/data/api/v2/item/211/index.json#L177

It should be something like this: "Este objeto restaura gradualmente durante el\ncombate los PS del Pok\u00e9mon que lo lleva."

**Comment by Naramsim** [comment]
Hi, could you fix that?

**Comment by Xing97** [comment]
#228
