### ISSUE TITLE
Sub resourcing

### ISSUE THREAD

**Issue by Naramsim** [PokeAPI/api-data#4]
According to https://github.com/PokeAPI/pokeapi/issues/180 a useful upgrade to a possible Pokeapi v2.1 could be subresourcing.

At that moment in time it seemed very difficult to implement it, and in fact, it was implemented only for the encounters key in the pokemon endpoint.

Right now I see the implementation of sub resourcing relatively easy. One could think of an invoking the API with a certain querystring to only query what he wants. 

https://pokeapi-prod.netlify.com/api/v2/pokemon/21/?keys=height,id,name

I'm not sure if the `keys` query parameter is a good name but I think that this idea could save us a large portion of bandwidth and an even more fast response time.

To implement this feature one could create a similar function to this one 
https://github.com/PokeAPI/api-data/blob/c1a800b808a0cc3b28be0013bf5c596deba6735d/functions/resource-list.js#L72-L102

**Comment by sargunv** [comment]
Closing for now, feel free to reopen if things change down the line.
