### ISSUE TITLE
Error 503 Backend unavailable, connection timeout

### ISSUE THREAD

**Issue by ElecTreeFrying** [PokeAPI/api-data#44]
I'm getting this error requesting to this url: https://raw.githubusercontent.com/PokeAPI/api-data/master/data/api/v2/pokemon/504/index.json

> Error 503 Backend unavailable, connection timeout
> Backend unavailable, connection timeout
> 
> Guru Mediation:
> Details: cache-hkg17929-HKG 1591171890 2855085221
> 
> Varnish cache server

**Comment by Naramsim** [comment]
Not on my side. That content is anyway served by Github itself.

Also, please use the API: https://pokeapi.co/api/v2/pokemon/504

**Comment by Naramsim** [comment]
Bump @ElecTreeFrying

**Comment by ElecTreeFrying** [comment]
I'm having problems 504 errors in some less than 10 id's in https://pokeapi.co/api/v2/pokemon/ that's why I'm fetching in this repo.

By the way. the url's working now ill close this issue thanks. @Naramsim
